### ISSUE TITLE
Feature Request: Search over all icon sets

### ISSUE THREAD

**Issue by bux** [hawkeye64/iconexplorer.app#12]
When looking for the perfect e.g. coffee icon, the search could look in all icon sets for a coffee icon and render all fitting ones. Right now (if I am not mistaken) one would need to click on each icon set on the left to apply the filter.

**Comment by hawkeye64** [comment]
@bux Yes, you are correct. However, there are over 55,000 icons now and more to come. Without a backend server to support a feature such as this, all the icon sets would have to be loaded so they could be searched through. I think the DX and UX would be crippling.

That being said, just the names without the SVG could be generated at build time and that could be searched as a reference.

I'll have to give it some thought because this is still a performance hit (55k+) names, etc.

We'll keep this ticket open until a decision is made.

**Comment by hawkeye64** [comment]
@bux I'm not sure if you're aware of it, but after entering text into the filter, you can select different icon sets and when they load, they'll automatically be filtered. And, because of the loading magic we do on icon sets it is pretty fast.

**Comment by bux** [comment]
Yes, I am aware of it. I agree it's fast 😄

**Comment by hawkeye64** [comment]
@bux This will be available (officially) in the next release. You can actually use it now.

https://user-images.githubusercontent.com/10262924/144936050-de46fd5d-372e-424c-8d17-edeca1d6820e.mp4

**Comment by bux** [comment]
♥
